.p2align 3            	  	// директива для выравнивания секции по  чётному адресу.	
.section .data.imu1
	.global _buffer_a
	_buffer_a: .space 1024<<3

.p2align 3            	  	// директива для выравнивания секции по  чётному адресу.	
.section .data.imu2
	.global _buffer_b
	_buffer_b: .space 1024<<3

.p2align 3            	  	// директива для выравнивания секции по  чётному адресу.	
.section .data.imu3
	.global _buffer_c
	_buffer_c: .space 1024<<3

.p2align 3            	  	// директива для выравнивания секции по  чётному адресу.	
.section .data.imu4
	.global _buffer_d
	_buffer_d: .space 1024<<3


